[id='gs-adding-custom-3scale-routes']

ifdef::env-github[]
:imagesdir: ../images/
endif::[]

= Creating custom URLss for 3scale APIs

NOTE: You cannot delete any routes created using the procedure described below.

If you use 3scale to manage your API, you might require that the API URL use a specific host and format.
For example, you might want to expose an API as `https://mydomain.com/v1/getStuff`.
To use a custom domain, you must create a route in the OpenShift 3scale project as described below.

.Prerequisites
* the `customer-admin` user credentials
* a custom domain registration

.Procedure

A new OpenShift route for the public has to be created.

. Log in as `customer-admin`:
+
[source,bash]
----
$ oc login -u customer-admin
----

. Create a file named `custom-route.yaml` using the appropriate values for `<route name>` and `<route host>`:
+
[source,yaml]
----
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: <route name>
  namespace: openshift-3scale
spec:
  host: <route host>
  port:
    targetPort: gateway
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
  to:
    kind: Service
    name: apicast-staging
    weight: 100
  wildcardPolicy: None
----

. Create the route:
+
[source,bash]
----
$ oc create -f ./custom-route.yaml
----

. Set up your public base URL in APIcast as described in the link:https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.4/html-single/deployment_options/index#configure_your_service[3scale documentation].

.Additional Information

See the link:https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.4/html-single/deployment_options/index#public_base_url[Public Base URL] documentation for an introduction to custom URLs.