:linkTroubleshooting: https://github.com/integr8ly/example-customisations/blob/master/docs/troubleshooting.adoc
:linkGitHubFork: https://help.github.com/articles/fork-a-repo/
:linkIndexURL: https://github.com/integr8ly/example-customisations/index.adoc

[id='gs-writing-walkthroughs-proc']
= Creating {PRODUCT} {walkthrough-name}s
:toc:

== About creating {walkthrough-name}s

To write {walkthrough-name}s you require a knowledge of:

* Asciidoc - a lightweight markup language, similar to markdown
* JSON - a lightweight format for storing and transporting data
* Git - you must push your Asciidoc and JSON files to a Git repository
* OpenShift - you can add {walkthrough-name}s using the OpenShift console

A simple {walkthrough-name} only requires that you edit an Asciidoc file, for example:

[source,asciidoc]
----
= Demonstrating features <1>

A short description for the feature. <2>

== Doing a task <3>

. Do this first: <4>
. Do this second:
----
<1> {walkthrough-name} title, you can only have a single level 1 heading per file.
<2> The first line of the introduction is displayed as a tag line for the {walkthrough-name} and displayed on the {webapp} home page.
Do not use AsciiDoc attributes in this line because they are not displayed correctly on the homepage.
<3> A task contains one or more subtasks (level 3 headings)
<4> A numbered list of steps the user must perform.

[type={walkthrough-name}Resource]
.Additional Resources
****
* link:http://asciidoc.org/[Asciidoc Homepage^]
* link:https://asciidoctor-docs.netlify.com/asciidoc/1.5/[AsciiDoc Syntax]
* link:https://github.com/evanshortiss/integreatly-vscode-asciidoc-snippets/[Visual Studio Code extension]
****

[time=10]
== Getting started

To get started with {walkthrough-name} development you can edit the template repository and learn about the components of a {walkthrough-name}.

=== Downloading the template

The template contains the directory structure along with a sample {walkthrough-name} and manifest file.

. Clone the template repository
+
[source,bash]
----
git clone https://github.com/integr8ly/walkthrough-template.git
----

. Change to the `walkthrough-template` directory:
+
[source,bash]
----
cd walkthrough-template
----


=== Understanding the file structure

[source]
----
.
├── walkthroughs-config.json <1>
└── walkthroughs<2>
    ├── <identifier> <3>
    │   ├── images <4>
    │   │   └── image.png
    │   ├── walkthrough.adoc <5>
    │   └── walkthrough.json <6>
    ├── <walkthrough2-id> <3>
    └── <walkthrough3-id> <3>
----


<1> This is an optional file that defines metadata for the set of Solution Patterns in the repository.

<2> This is a required directory. All {walkthrough-name}s are defined under `walkthroughs`.

<3> The directory name of a {walkthrough-name}. This is also displayed in the URL of {webapp}.

<4> All images for the {walkthrough-name}.

<5> *walkthrough.adoc* is where the content of the {walkthrough-name} is written in Asciidoc format.

<6> *walkthrough.json* is the manifest file of the {walkthrough-name} where you can define extra dependencies.


The default `walkthrough.json` does not define any dependent services:

[source,json]
----
{
  "dependencies": {
    "repos": [],
    "serviceInstances": []
  }
}
----

=== Committing your {walkthrough-name}s to a remote repository

You can edit the `walkthrough.adoc` file and push your changes to GitHub.

. Create a new remote repository and take note of the remote URL.

. Add the remote to your local clone.
+
[source,bash]
----
git remote add upstream <remote URL>
----

. Commit your changes.

. Push your changes.
+
[source,bash]
----
git push -u upstream master
----


[time=5]
== Editing overview sections of a {PRODUCT} {walkthrough-name}

The first section of the `walkthrough.adoc` describes your {walkthrough-name},it provides an overview of the purpose of the {walkthrough-name}.
The overview is displayed when a user clicks on the {walkthrough-name} in {webapp}.

* The overview is defined by a first level heading (in AsciiDoc a line begining with `=`) and finishes at the next second level heading (`==`).
* The title of the overview becomes the name of the {walkthrough-name}.
* The overview heading must be followed by a paragraph giving a short introduction to the {walkthrough-name} in one or two sentences.
This description is displayed in the {webapp} dashboard card for the {walkthrough-name}.

.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].


.Procedure

To add an overview section using the template respository:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Change the title of the {walkthrough-name}, for example:
+
[subs="attributes"]
----
= My first {walkthrough-name}
----

. Add an introduction paragraph to your preamble.

. Add another paragraph with more information about the {walkthrough-name}.

. Commit your changes
+
----
git commit -am "add overview"
----

. Push your change to the remote repository
+
----
git push upstream master
----


[time=5]
== Editing task sections of a {PRODUCT} {walkthrough-name}

.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].

Tasks are procedures that you write as a section of the `walkthrough.adoc` file, the section being defined by a second level heading (`==`).

.Procedure

The template already contains a sample task, you can change it as follows:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Change the task title, for example, `== Doing the first task`.

. Write a short introduction to the task.

. Change the task timing estimate. Each task has an attribute to communicate the approximate time that the task should take the user to perform.
+
This is displayed in the {walkthrough-name} overview as part of the task list.
+
For example to change the estimated time for the first task to 12 minutes:
+
----
[time=12]
== Doing the first task
----

. Save, commit and push your changes.
+
NOTE: The content of the {webapp} does not change automatically after a change in the subscribed repository. You must redeploy the {webapp} for the change to be visible.

+
. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.

+
NOTE: You can create another level of subtasks by creating a third level heading (`===`). Subtasks are displayed in the {webapp} on the parent task page.



[time=5]
== Editing procedures of a {PRODUCT} {walkthrough-name}

A procedure is a set of steps that you perform to complete a task or subtask.

Write procedures using AsciiDoc numbered lists.
Prepend each step with a `.` to create a simple numbered list.


.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].


.Procedure

To edit a procedure in the template respository:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Edit the numbered list:
+
----
. First step
. Second step
. Third step
----

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.


[time=5]
== Editing {walkthrough-name} resources for a {PRODUCT} {walkthrough-name}

The {webapp} can display helpful information and links on the right hand side panel.

.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].


.Procedure

To add a {walkthrough-name} resources:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Add {walkthrough-name} resources using block attributes at the end of the overview section, for example:
+
[source,asciidoc]
----
[type=walkthroughResource,serviceName=openshift]
.OpenShift
****
* link:{openshift-host}[Openshift Console, window="_blank"]
****
----

+
[NOTE]
====
* Setting `serviceName` is optional.

* If `serviceName` is set to the name of a middleware service, an icon indicating the service status is displayed next to the resource.

* For a list of default services, see link:https://github.com/integr8ly/tutorial-web-app/blob/master/src/common/serviceInstanceHelpers.js[the value for DEFAULT_SERVICES].

* Setting the `window="_blank"` parameter for a {walkthrough-name} resource link is also optional, but ensures that the target of the link displays in a separate browser tab.
====
+
NOTE: You can only define {walkthrough-name} resources in the overview section.

+

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.


[time=5]
== Editing task resources for a {PRODUCT} {walkthrough-name}

The {webapp} can display helpful information and links on the right hand side panel that are specific to a task.
{walkthrough-name} resources are displayed for every task, whereas task resources typically change as the user navigates the {walkthrough-name}.

.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].


.Procedure

To add task resources:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. At the end any task section, add the following:
+
----
[type=taskResource]
.Useful links
****
* link:https://google.com[Task related link]
****
----

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.


[time=10]
== Adding verifications to a {PRODUCT} {walkthrough-name}
Verifications are interactive elements in a {walkthrough-name} that confirm whether a user has successfully completed a procedure. They are questions presented to the user, which can be answered with either a `Yes` or `No` response.

NOTE: Every procedure in a task or subtask requires a verification.


.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].


.Procedure

To add a verification:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. At the end of the procedure section, following the numbered list add:
+
:verificationText: verification
[source,asciidoc,subs="attributes"]
----
[type={verificationText}]
Check that the dashboard of service X reports no errors.
----
. Add the following block to cater for users that answer the question with `No`:
+
[source,asciidoc]
----
[type=verificationFail]
Try turning it off and on again.
----

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.


[time=5]
== Adding attributes to a {PRODUCT} {walkthrough-name}

Attributes are used to make external variable users performing a {walkthrough-name}.
The syntax for using attributes is `{<attribute name>}`. {walkthrough-name}s have access to a number of predefined attributes:

* If a middleware service defines a route you can access it using `{route-<route name>-host}`.

* The OpenShift console is available as `\{openshift-host}`.

Other attributes that are available to {walkthrough-name} authors are:

* Default attributes:
** OpenShift App Host: `\{openshift-app-host}`
** CodeReady Workspaces URL: `\{che-url}`.
** Fuse URL: `\{fuse-url}`
** Launcher URL: `\{launcher-url}`
** API Management URL: `\{api-management-url}`
** AMQ Online URL: `\{enmasse-url}`
** AMQ Online Broker URL: `\{enmasse-broker-url}`
** AMQ Online Credential Username: `\{enmasse-credentials-username}`
** AMQ Online Credential Password: `\{enmasse-credentials-password}`
* Custom attributes:
** NodeJS Frontend App Route (provisioned from walkthrough.json): `\{route-frontend-host}`


.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].


.Procedure

To add a link to the OpenShift console in the {walkthrough-name}:

. Add another step to the numbered list in your procedure:
+
----
. Click on the link to the OpenShift console.
----
+
. Save, commit and push your changes.
. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.



[time=10]
== Adding custom services to a {PRODUCT} {walkthrough-name}

You can create services from the OpenShift catalog in the cluster as part of the {walkthrough-name} startup process.
You can also link to the URLs associated with those services in your `walkthrough.adoc` file.


.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[].
* Some experience with the `oc` command. See link:https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html[Getting Started with the OpenShift CLI] for more information about `oc` command.


.Procedure

. Find the name of the service you want to provision:

.. Log in to the OpenShift console.

.. Click your username in the top right corner and choose *Copy Login Command* from the menu.

.. Log in to the OpenShift CLI using the `oc` on your clipboard.

.. Run the following command to list all the service names available from your cluster catalog:
+
----
oc get clusterserviceclasses -o custom-columns="Display Name (From Service Catalog):.spec.externalMetadata.displayName, Identifier (clusterServiceClassExternalName):.spec.externalName"
----
+
The output lists all the services available in two columns:
+
* Display Name (From Service Catalog)
* Identifier (clusterServiceClassExternalName)

.. Choose the service you want to use, and note the value in the `Identifier (clusterServiceClassExternalName)` column.
+
For example, to use the `CakePHP + MySQL (Ephemeral)` service in your custom {walkthrough-name}, note the value `cakephp-mysql-example`.

. Create a `walkthrough.json` with the following contents to provision the `cakephp-mysql-example` service:
+
----
{
    "dependencies": {
        "repos": [],
        "serviceInstances": [
            {
                "metadata": {
                    "name": "cakephp-mysql-example"
                },
                "spec": {
                    "clusterServiceClassExternalName": "cakephp-mysql-example",
                    "clusterServicePlanExternalName": "default"
                }
            }
        ]
    }
}
----
+
. Add your {walkthrough-name} to the cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].
. Navigate the {walkthrough-name} to trigger the provisioning of the custom service, for example, the `cakephp-mysql-example` service.
. Log in to the OpenShift console.
. Navigate to the custom project in OpenShift.The project is named using the pattern `<username>-<walkthrough-id>`.
. Open *Routes* from the *Applications* menu.
. Note the *Name* of the route you want to reference in your {walkthrough-name} tasks. For example, `cakephp-mysql-example`.
. Edit the `walkthrough.adoc` file and use the `{route-<route-name>-host}` pattern, whenever you want the route URL to appear.
For example, to insert a step that asks the user of the {walkthrough-name} to log in to the CakePHP app:
+
----
. Log into the link:{route-cakephp-mysql-example-host}[CakePHP app].
----
+
NOTE: If you want Asciidoc attributes to render values in code blocks, you must start the code block with `[subs="attributes"]`.

+
. Redeploy the *tutorial-web-app* to pick up changes to your {walkthrough-name}.
. Log in to the {webapp} using a different username to test the {walkthrough-name}.


== Defining metadata for your {walkthrough-name} repository

By default, the {walkthrough-name}s from a repository are displayed in {webapp} with a title corresponding to your repository name. You can add a `walkthroughs-config.json` file with the following contents if, for example, you want to title the group `My {walkthrough-name}s`:


[source, json]
----
{
    "prettyName": "My Solution Patterns"
}
----

== Previewing your {walkthrough-name}

. Log in to the {webapp}
. Follow the steps described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].
