[id='assembly_release-notes']

include::attributes.adoc[]

:gs-link: :rn-link: ../getting-started/


= Release Notes for Managed Integration {MINOR_VERSION_NO}

// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: images
:context: release-notes

// Purpose statement for the assembly
These release notes list the components of {PRODUCT} {PATCH_VERSION_NO}, as well as known and fixed issues in this release.

NOTE: When a {PRODUCT_SHORT} patch or upgrade is available, you are notified and prompted to create an upgrade schedule. 
When prompted, see these Release Notes for details regarding changes to your cluster.

[IMPORTANT]
====
{PRODUCT_SHORT} is a Technology Preview feature only. Technology Preview features are 
not supported with Red Hat production service level agreements (SLAs) and might not be 
functionally complete. Red Hat does not recommend using them in production. 
These features provide early access to upcoming product features, enabling 
customers to test functionality and provide feedback during the development process. 
For more information about the support scope of Red Hat Technology Preview features, 
see https://access.redhat.com/support/offerings/techpreview/. 
====

include::_partials/rn-versions-ref.adoc[leveloffset=+1]

include::_partials/rn-fixed-issues-ref.adoc[leveloffset=+1]

include::_partials/rn-known-issues-ref.adoc[leveloffset=+1]

include::_partials/rn-new-and-changed-ref.adoc[leveloffset=+1]
