= Troubleshooting Guide

include::attributes.adoc[]

= Getting started with {PRODUCT}
// Context attribute is assembly specific and enables module reuse between assemblies.
:imagesdir: images
:context: getting-started
:customer-realm-name: customer-applications
:rn-link: https://integr8ly.github.io/user-documentation/index.html?e=docs/troubleshooting.adoc


NOTE: Refer to the link:{rn-link}[Release Notes] for the latest troubleshooting tips for {PRODUCT_SHORT}.


// Purpose statement for the assembly
This document provides troubleshooting instructions for new users of {PRODUCT_SHORT}.
// and subsequent patch releases.


---
= Day In The Life Workshop Troubleshooting Guide

== Inaccessible consoles

Fix for issue where certain administrative consoles become inaccessible (after Integreatly cluster shutdown and restart):

. Check pod status within the OpenShift project where console service is found:
+
[source,bash]
----
$ oc get po -n <project_name>
----

. Identify unstable pod(s). In this example, *codeready-6ff4c6ccb8-2lr6k* pod is unstable.
+
[source,bash]
----
NAME                                  READY     STATUS       RESTARTS     AGE
codeready-6ff4c6ccb8-2lr6k            0/1       CrashLoopBack   87         5h
codeready-operator-7547984678-jzpc6   1/1       Running         3          5h
postgres-95db94985-p7m2s              1/1       Running         1          1h
----

. Delete the unstable pod:
+
[source,bash]
----
$ oc delete pod codeready-6ff4c6ccb8-rk7wf
----

. Check pod status in real-time within the OpenShift project:
+
[source,bash]
----
$ oc get po -w -n <project_name>
----
+
NOTE: Notice that a new pod, containing the same service, is created to replace the deleted pod.

5. (Optional) If the problem of unstable pod(s) persist, delete other pod(s) that the unstable pod(s) are dependent on.
* *For instance, the unstable pod in the example is dependent on the Postgresql database pod.*
* *Delete the Postgresql database pod, and once it is fully active, delete the unstable CodeReady Workspaces pod.*

6. Tail the pod log in order to observe startup process:
+
[source,bash]
----
$ oc logs -f codeready-6ff4c6ccb8-rk7wf
----
