// Metadata created by nebel
//
// QuickstartID: 
// Level: 2
// ParentAssemblies: assemblies/getting-started/as_getting-started.adoc
// UserStory: 
// VerifiedInVersion: 

[id="what-is-solution-explorer"]
= What is Solution Explorer?
//In the title of concept modules, include nouns or noun phrases that are used in the body text. This helps readers and search engines find the information quickly.
//Do not start the title of concept modules with a verb. See also _Wording of headings_ in _The IBM Style Guide_.


The {webapp} presents links to the applications available in a {PRODUCT_SHORT} cluster. The {webapp} provides Solution Patterns that guide users through the process of creating various integrated solutions using these applications.


{PRODUCT_SHORT} provides access to the following consoles:

* *OpenShift*, the OpenShift cluster console.

* *API Designer*,  the Apicurito RESTful API visual designer.

* *Red Hat 3scale API Management*, a platform that provide RESTful API Management.

* *Red Hat AMQ*, fast, lightweight, and secure messaging for Internet-scale applications.

* *Red Hat CodeReady Workspaces*, a developer workspace server and cloud IDE.

* *Red Hat Fuse Online*, a facility to obtain data from an application or service, operate on that data, and then send the data to another application or service without writing code.

* *Push Notifications*, a service to push notifications to Android and iOS devices.

* *Red Hat Single Sign-On*, a single sign-on solution for web apps and RESTful web services. 

+
[NOTE]
====
Most applications are available in the {webapp}, after you log in; however, if *Red Hat AMQ Online* is not available, the *Start service* button is displayed. Click *Start service* to provision it.
====

