[id='rn-new-and-changed-ref']
= New and changed features

== New component versions

This release includes new versions of the following components:

[cols="h,"]
|===

|Component
|Release Notes

|{fuse-name}
|link:https://access.redhat.com/documentation/en-us/red_hat_fuse/7.5/html/release_notes_for_red_hat_fuse_7.5/index[{fuse-version}]

|{amq-online-name}
|link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.5/html/release_notes_for_amq_online_1.3_on_openshift/index[{amq-online-version}]

|{three-scale-name}
|link:https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.7/html/release_notes_for_red_hat_3scale_api_management_2.7_on-premises/index[{three-scale-version}]

|===

== Solution Explorer changes

The Solution Explorer homepage now provides more information on the applications in your cluster, listing the goals you can accomplish with each service. 
The Solution Patterns are available in a separate tab, named *All Solution Patterns*.

In addition, you can now:

* Navigate to the Git repository of any set of Solution Patterns in your cluster. 
See link:{gs-link}#gs-publishing-walkthroughs-proc[Adding Solution Patterns to your cluster] for more information about navigating to a source repository.

* Retrieve useful URLs for your cluster from the help menu of Solution Explorer.
See link:{gs-link}#gs-accessing-developer-resources-proc[Using Developer Resources] for more information.


== Mobile features

* Mobile Security Service - The Mobile Security Service is no longer available.

* Mobile Developer Console - The Mobile Developer Console is no longer available. 
The Push Admin UI is now linked directly from the Solution Explorer.

* Mobile Developer Services - This documentation no longer refers to Mobile Developer Services. 
The documentation is now separated as follows:

** The Data Sync framework documentation provides all the steps required to implement data sync features in a web or mobile app.
** The *Adding Data Sync to your Application with GraphQL* demonstrates the data sync features and shows you how to implement authentication and authorization in your web or mobile app.
** The Push Notification Service documentation shows you how to implement push notifications in your mobile app.
