:PRODUCT: Red Hat Managed Integration
:ProductName: {PRODUCT}
:PRODUCT_SHORT: Managed Integration
:PRODUCT_INIT: rhmi
:PRODUCT_INIT_CAP: RHMI

:PRODUCT_VERSION: 2
:ProductRelease: {PRODUCT_VERSION}
:MINOR_VERSION_NO: 2.0
:PATCH_VERSION_NO: 2.0.0

:cluster-suffix: <cluster suffix>
:suffix-example: example.u7y2.s1.openshift.com

:URL_COMPONENT_PRODUCT: red_hat_managed_integration

:URL_BASE_GITHUB: https://github.com/integr8ly/user-documentation

:webapp: Solution Explorer
:walkthrough-name: Solution Pattern

:cluster-administrator: cluster administrator
:cluster-developer: developer user

//:rhmi-sso-name: Managed Integration SSO instance
:customer-sso-name: Customer Application SSO instance
:rhsso-name: Red Hat Single Sign-On

:fuse-name: Red Hat Fuse Online
:fuse-version: 7.5
:fuse-docs: https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/
:fuse-configs: https://access.redhat.com/articles/310603

:amq-online-name: Red Hat AMQ Online
:amq-online-version: 1.3
:amq-online-docs: https://access.redhat.com/documentation/en-us/red_hat_amq/
:amq-online-configs: https://access.redhat.com/articles/2791941

:three-scale-name: Red Hat 3scale API Management
:three-scale-version: 2.8
:three-scale-docs: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/{three-scale-version}/
:three-scale-configs: https://access.redhat.com/articles/2798521

:code-ready-name: Red Hat CodeReady Workspaces for OpenShift
:code-ready-short: CodeReady Workspaces
:code-ready-version: 2.0
:code-ready-docs: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/{code-ready-version}/
:code-ready-configs: N/A
:codeready-workspaces-url: https://codeready-redhat-rhmi-codeready-workspaces.apps.{cluster-suffix}

[id="assembly_creating-solution-patterns"]

:PRODUCT: Red Hat Managed Integration
:ProductName: {PRODUCT}
:PRODUCT_SHORT: Managed Integration
:PRODUCT_INIT: rhmi
:PRODUCT_INIT_CAP: RHMI

:PRODUCT_VERSION: 2
:ProductRelease: {PRODUCT_VERSION}
:MINOR_VERSION_NO: 2.0
:PATCH_VERSION_NO: 2.0.0

:cluster-suffix: <cluster suffix>
:suffix-example: example.u7y2.s1.openshift.com

:URL_COMPONENT_PRODUCT: red_hat_managed_integration

:URL_BASE_GITHUB: https://github.com/integr8ly/user-documentation

:webapp: Solution Explorer
:walkthrough-name: Solution Pattern

:cluster-administrator: cluster administrator
:cluster-developer: developer user

//:rhmi-sso-name: Managed Integration SSO instance
:customer-sso-name: Customer Application SSO instance
:rhsso-name: Red Hat Single Sign-On

:fuse-name: Red Hat Fuse Online
:fuse-version: 7.5
:fuse-docs: https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/
:fuse-configs: https://access.redhat.com/articles/310603

:amq-online-name: Red Hat AMQ Online
:amq-online-version: 1.3
:amq-online-docs: https://access.redhat.com/documentation/en-us/red_hat_amq/
:amq-online-configs: https://access.redhat.com/articles/2791941

:three-scale-name: Red Hat 3scale API Management
:three-scale-version: 2.8
:three-scale-docs: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/{three-scale-version}/
:three-scale-configs: https://access.redhat.com/articles/2798521

:code-ready-name: Red Hat CodeReady Workspaces for OpenShift
:code-ready-short: CodeReady Workspaces
:code-ready-version: 2.0
:code-ready-docs: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/{code-ready-version}/
:code-ready-configs: N/A
:codeready-workspaces-url: https://codeready-redhat-rhmi-codeready-workspaces.apps.{cluster-suffix}

= Creating Solution Patterns for Red Hat Managed Integration 2.0

:context: creating-solution-patterns

// Purpose statement for the assembly
This document provides instructions for creating Solution Patterns.



Unresolved directive in creating-solution-patterns.adoc - include::modules/creating-sps/proc_about-creating-solution-pattern.adoc[leveloffset=+1]

:leveloffset: +1

[id='downloading-solution-pattern-template']


= Downloading the Solution Pattern template

To get started with Solution Pattern development you can edit the template repository and learn about the components of a Solution Pattern.


The template contains the directory structure along with a sample Solution Pattern and manifest file.

.Procedure
. Clone the template repository
+
[source,bash]
----
git clone https://github.com/integr8ly/walkthrough-template.git
----

. Change to the `walkthrough-template` directory:
+
[source,bash]
----
cd walkthrough-template
----

:leveloffset!:

:leveloffset: +1

[id='understanding-file-structure']


= Understanding the file structure

[source]
----
.
├── walkthroughs-config.json <1>
└── walkthroughs<2>
    ├── <identifier> <3>
    │   ├── images <4>
    │   │   └── image.png
    │   ├── walkthrough.adoc <5>
    │   └── walkthrough.json <6>
    ├── <walkthrough2-id> <3>
    └── <walkthrough3-id> <3>
----


<1> This is an optional file that defines metadata for the set of {Solution Patterns} in the repository.

<2> This is a required directory. All Solution Patterns are defined under `walkthroughs`.

<3> The directory name of a Solution Pattern. This is also displayed in the URL of {webapp}.

<4> All images for the Solution Pattern.

<5> *walkthrough.adoc* is where the content of the Solution Pattern is written in Asciidoc format.

<6> *walkthrough.json* is the manifest file of the Solution Pattern where you can define extra dependencies.


The default `walkthrough.json` does not define any dependent services:

[source,json]
----
{
  "dependencies": {
    "repos": [],
    "serviceInstances": []
  }
}
----

:leveloffset!:

:leveloffset: +1

[id='committing-solution-pattern-remote-repository']


= Committing your Solution Pattern to a remote repository

You can edit the `walkthrough.adoc` file and push your changes to GitHub.

.Procedure
. Create a new remote repository and take note of the remote URL.

. Add the remote to your local clone.
+
[source,bash]
----
git remote add upstream <remote URL>
----

. Commit your changes.

. Push your changes.
+
[source,bash]
----
git push -u upstream master
----


:leveloffset!:

:leveloffset: +1

[id='editing-overview-section-solution-pattern']


= Editing the overview section of a {PRODUCT} Solution Pattern

The first section of the `walkthrough.adoc` describes your Solution Pattern,it provides an overview of the purpose of the Solution Pattern.
The overview is displayed when a user clicks on the Solution Pattern in {webapp}.

* The overview is defined by a first level heading (in AsciiDoc a line begining with `=`) and finishes at the next second level heading (`==`).
* The title of the overview becomes the name of the Solution Pattern.
* The overview heading must be followed by a paragraph giving a short introduction to the Solution Pattern in one or two sentences.
This description is displayed in the {webapp} dashboard card for the Solution Pattern.

.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Adding Solution Patterns].


.Procedure
To add an overview section using the template respository:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Change the title of the Solution Pattern, for example:
+
[subs="attributes"]
----
= My first Solution Pattern
----

. Add an introduction paragraph to your preamble.

. Add another paragraph with more information about the Solution Pattern.

. Commit your changes
+
----
git commit -am "add overview"
----

. Push your change to the remote repository
+
----
git push upstream master
----

:leveloffset!:

:leveloffset: +1

[id='editing-task-sections-solution-pattern']


= Editing task sections of a {PRODUCT} Solution Pattern

.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Adding Solution Patterns].

Tasks are procedures that you write as a section of the `walkthrough.adoc` file, the section being defined by a second level heading (`==`).

.Procedure
The template already contains a sample task, you can change it as follows:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Change the task title, for example, `== Doing the first task`.

. Write a short introduction to the task.

. Change the task timing estimate. Each task has an attribute to communicate the approximate time that the task should take the user to perform.
+
This is displayed in the Solution Pattern overview as part of the task list.
+
For example to change the estimated time for the first task to 12 minutes:
+
----
[time=12]
== Doing the first task
----

. Save, commit and push your changes.
+
NOTE: The content of the {webapp} does not change automatically after a change in the subscribed repository. You must redeploy the {webapp} for the change to be visible.

+
. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.

+
NOTE: You can create another level of subtasks by creating a third level heading (`===`). Subtasks are displayed in the {webapp} on the parent task page.


:leveloffset!:

:leveloffset: +1

[id='editing-procedures-solution-pattern']


= Editing procedures of a {PRODUCT} Solution Pattern

A procedure is a set of steps that you perform to complete a task or subtask.

Write procedures using AsciiDoc numbered lists.
Prepend each step with a `.` to create a simple numbered list.


.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Adding Solution Patterns].


.Procedure
To edit a procedure in the template respository:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Edit the numbered list:
+
----
. First step
. Second step
. Third step
----

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.

:leveloffset!:

:leveloffset: +1

[id='editing-resources-solution-pattern']


= Editing resources for a {PRODUCT} Solution Pattern

The {webapp} can display helpful information and links on the right side panel.

.Prerequisites
* You have created a repository using the Solution Patterns template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Adding Solution Patterns].


.Procedure
To add a Solution Pattern resources:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Add Solution Pattern resources using block attributes at the end of the overview section, for example:
+
[source,asciidoc]
----
[type=walkthroughResource,serviceName=openshift]
.OpenShift
****
* link:{openshift-host}[Openshift Console, window="_blank"]
****
----

+
[NOTE]
====
* Setting `serviceName` is optional.

* If `serviceName` is set to the name of a middleware service, an icon indicating the service status is displayed next to the resource.

* For a list of default services, see link:https://github.com/integr8ly/tutorial-web-app/blob/master/src/common/serviceInstanceHelpers.js[the value for DEFAULT_SERVICES].

* Setting the `window="_blank"` parameter for a Solution Pattern resource link is also optional, but ensures that the target of the link displays in a separate browser tab.
====
+
NOTE: You can only define Solution Pattern resources in the overview section.

+

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.

:leveloffset!:

:leveloffset: +1

[id='editing-task-resources-solution-pattern']



= Editing task resources for a {PRODUCT} Solution Pattern

The {webapp} can display helpful information and links on the right hand side panel that are specific to a task.
Solution Pattern resources are displayed for every task, whereas task resources typically change as the user navigates the Solution Pattern.

.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Adding Solution Patterns].


.Procedure
To add task resources:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. At the end any task section, add the following:
+
----
[type=taskResource]
.Useful links
****
* link:https://google.com[Task related link]
****
----

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.

:leveloffset!:

:leveloffset: +1

[id='adding-verifications-solution-pattern']


= Adding verifications to a {PRODUCT} Solution Pattern
Verifications are interactive elements in a Solution Pattern that confirm whether a user has successfully completed a procedure. They are questions presented to the user, which can be answered with either a `Yes` or `No` response.

NOTE: Every procedure in a task or subtask requires a verification.


.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Adding Solution Patterns].


.Procedure
To add a verification:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. At the end of the procedure section, following the numbered list add:
+
:verificationText: verification
[source,asciidoc,subs="attributes"]
----
[type={verificationText}]
Check that the dashboard of service X reports no errors.
----
. Add the following block to cater for users that answer the question with `No`:
+
[source,asciidoc]
----
[type=verificationFail]
Try turning it off and on again.
----

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.

:leveloffset!:

:leveloffset: +1

[id='adding-attributes-solution-pattern']


= Adding attributes to a {PRODUCT} Solution Pattern

Attributes are used to make external variable users performing a Solution Pattern.
The syntax for using attributes is `{<attribute name>}`. Solution Patterns have access to a number of predefined attributes:

* If a middleware service defines a route you can access it using `{route-<route name>-host}`.

* The OpenShift console is available as `\{openshift-host}`.

Other attributes that are available to Solution Pattern authors are:

* Default attributes:
** OpenShift App Host: `\{openshift-app-host}`
** CodeReady Workspaces URL: `\{che-url}`.
** Fuse URL: `\{fuse-url}`
** Launcher URL: `\{launcher-url}`
** API Management URL: `\{api-management-url}`
** AMQ Online URL: `\{enmasse-url}`
** AMQ Online Broker URL: `\{enmasse-broker-url}`
** AMQ Online Credential Username: `\{enmasse-credentials-username}`
** AMQ Online Credential Password: `\{enmasse-credentials-password}`


.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Adding Solution Patterns].


.Procedure
To add a link to the OpenShift console in the Solution Pattern:

. Add another step to the numbered list in your procedure:
+
----
. Click on the link to the OpenShift console.
----
+
. Save, commit, and push your changes.
. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.


:leveloffset!:

:leveloffset: +1

[id='adding-custom-services-solution-pattern']


= Adding custom services to a {PRODUCT} Solution Pattern

You can create services from the OpenShift catalog in the cluster as part of the Solution Pattern startup process.
You can also link to the URLs associated with those services in your `walkthrough.adoc` file.


.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in link:{adding-sps}[Publishing Solution Patterns].
* Some experience with the `oc` command. See link:https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html[Getting Started with the OpenShift CLI] for more information about `oc` command.


.Procedure
. Find the name of the service you want to provision:

.. Log in to the OpenShift console.

.. Click your username in the top right corner and choose *Copy Login Command* from the menu.

.. Log in to the OpenShift CLI using the `oc` on your clipboard.

.. Run the following command to list all the service names available from your cluster catalog:
+
----
oc get clusterserviceclasses -o custom-columns="Display Name (From Service Catalog):.spec.externalMetadata.displayName, Identifier (clusterServiceClassExternalName):.spec.externalName"
----
+
The output lists all the services available in two columns:
+
* Display Name (From Service Catalog)
* Identifier (clusterServiceClassExternalName)

.. Choose the service you want to use, and note the value in the `Identifier (clusterServiceClassExternalName)` column.
+
For example, to use the `CakePHP + MySQL (Ephemeral)` service in your custom Solution Pattern, note the value `cakephp-mysql-example`.

. Create a `walkthrough.json` with the following contents to provision the `cakephp-mysql-example` service:
+
----
{
    "dependencies": {
        "repos": [],
        "serviceInstances": [
            {
                "metadata": {
                    "name": "cakephp-mysql-example"
                },
                "spec": {
                    "clusterServiceClassExternalName": "cakephp-mysql-example",
                    "clusterServicePlanExternalName": "default"
                }
            }
        ]
    }
}
----
+
. Add your Solution Pattern to the cluster as described in link:{adding-sps}[Adding Solution Patterns].
. Navigate the Solution Pattern to trigger the provisioning of the custom service, for example, the `cakephp-mysql-example` service.
. Log in to the OpenShift console.
. Navigate to the custom project in OpenShift.The project is named using the pattern `<username>-<walkthrough-id>`.
. Open *Routes* from the *Applications* menu.
. Note the *Name* of the route you want to reference in your Solution Pattern tasks. For example, `cakephp-mysql-example`.
. Edit the `walkthrough.adoc` file and use the `{route-<route-name>-host}` pattern, whenever you want the route URL to appear.
For example, to insert a step that asks the user of the Solution Pattern to log in to the CakePHP app:
+
----
. Log into the link:{route-cakephp-mysql-example-host}[CakePHP app].
----
+
NOTE: If you want Asciidoc attributes to render values in code blocks, you must start the code block with `[subs="attributes"]`.

+
. Redeploy the *tutorial-web-app* to pick up changes to your Solution Pattern.
. Log in to the {webapp} using a different username to test the Solution Pattern.

:leveloffset!:

:leveloffset: +1

[id='defining-metadata-solution-pattern-repository']



= Defining metadata for your Solution Pattern repository

By default, the Solution Patterns from a repository are displayed in {webapp} with a title corresponding to your repository name. You can add a `walkthroughs-config.json` file with the following contents if, for example, you want to title the group `My Solution Patterns`:


[source, json]
----
{
    "prettyName": "My Solution Patterns"
}
----


:leveloffset!:

:leveloffset: +1

[id='previewing-solution-pattern']


= Previewing your Solution Pattern

.Procedure
. Log in to the {webapp}
. Follow the steps described in Adding Solution Patterns

:leveloffset!:


// Restore the context to what it was before this assembly.
:!context:
