[id='gs-adding-custom-idp']

ifdef::env-github[]
:imagesdir: ../images/
endif::[]

= Adding custom identity providers to {PRODUCT}

By default, {PRODUCT_SHORT} includes a Single Sign-On solution using Red Hat Single Sign-On (RHSSO).
This lets users log in to all the middleware services using the same accounts.

Red Hat Single Sign-On allows an administrator to use identity brokering for the {PRODUCT_SHORT} realm.

This section describes how to add a custom identity provider to Red Hat Single Sign-On.


.Prerequisite
* You are logged in to OpenShift as the `customer-admin` user.


.Procedure

. Log in to the Red Hat Single Sign-On administration console using the URL and credentials you received in your welcome email.

. Make sure the `openshift` realm is selected on the top left drop down.

. In the menu navigate to `Identity Providers` and pick a provider from the drop down.

. Follow the instructions in the link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.3/html/server_administration_guide/identity_broker[Red Hat Single Sign-On documentation] to add a new identity provider.
