[id='gs-publishing-walkthroughs-proc']
= Adding {walkthrough-name}s to your {PRODUCT} cluster

The home page of {webapp} lists the {walkthrough-name}s from all the Git repositories you are subscribed to. Any user can add {walkthrough-name}s to your cluster.

For more information on writing {walkthrough-name}s, see documentation on xref:gs-writing-walkthroughs-proc[Creating {walkthrough-name}s].

Note: You can access the Git repository that contains the {walkthrough-name} source code by clicking the *Repository* link located in the upper right corner of each group of Solution Patterns on the *All Solutions Patterns* tab in the Solution Explorer.

This procedure describes how to subscribe your cluster to a Git repository that contains {walkthrough-name}s.


.Procedure

. Navigate to the *Solution Explorer*.

. Click the gear icon in the top right to display the *Application settings* screen.

. Enter the URLs of the *Solution Pattern* repositories you want to add to your cluster. For example:
+
----
https://github.com/integr8ly/example-customisations.git#master
----
+
[NOTE]
====
* Enter one URL per line.
* To include a specific branch, use the syntax `#<branch-name>`.
* List URLs in the order you want them to appear on the homepage.
====

. Click *Save*.
+
Editing the value triggers an automatic redeployment of {webapp}.

. When the deployment is complete, refresh your browser.
+
You should now see new {walkthrough-name}s available from the dashboard.
+
[NOTE]
====
If the Git repository is updated with new content, {webapp} is not automatically updated.
To redeploy:

. Open the Openshift Console.
. Find and open the *webapp* project.
. Find and open the *tutorial-web-app* deployment.
. Click the *Deploy* button.

====
