[id='concept-explanation-{context}']
= Overview of {PRODUCT}

Red Hat Managed Integration delivers managed integration services hosted on the leading container platform, enabling diverse developers to engage in agile, microservices-based application development.
{PRODUCT_SHORT} enables your team to develop, build and deploy enterprise integration solutions on an OpenShift Dedicated cluster managed by Red Hat.
{PRODUCT_SHORT} enables developers to adopt event-based computing and API-based development with lightweight, loosely coupled, self-service and flexible components.
{PRODUCT_SHORT} enables the operations team to focus on high value objectives while Red Hat manage the infrastructure. All the applications and services are protected by Red Hat Single Sign-On.

== Solution Explorer

The {webapp} presents links to the applications available in a {PRODUCT_SHORT} cluster and provides {walkthrough-name}s that guide users through the process of creating various integrated solutions using these applications.

== Applications available in {webapp}

{PRODUCT_SHORT} provides access to the following consoles:

* *OpenShift*, the OpenShift cluster console.

* *API Designer*,  the Apicurito RESTful API visual designer.

* *Red Hat 3scale API Management*, a platform that provide RESTful API Management.

* *Red Hat AMQ*, fast, lightweight, and secure messaging for Internet-scale applications.

* *Red Hat CodeReady Workspaces*, a developer workspace server and cloud IDE.

* *Red Hat Developer Launcher*, a platform for continuous application delivery, with a set of templates.

* *Red Hat Fuse Online*, a facility to obtain data from an application or service, operate on that data, and then send the data to another application or service without writing code.

* *Push Notifications*, a service to push notifications to Android and iOS devices.

* *Red Hat Single Sign-On*, a single sign-on solution for web apps and RESTful web services. Two instances are available as described in xref:sso[].

+
[NOTE]
====
Most applications are available in the {webapp}, after you first log in.  However:

* If *Red Hat AMQ Online* is not available, the *Start service* button is displayed. Click *Start service* to provision it.
* You automatically have access to a shared instance of Fuse Online from the *Applications* menu, and if you start a {walkthrough-name}, you also provision an instance of Fuse Online which is not shared with other cluster users.
====


.Additional resources

* https://access.redhat.com/documentation/en-us/openshift_dedicated/3/[Product Documentation for OpenShift Dedicated 3]

== About {walkthrough-name}s

{walkthrough-name}s are tutorials available in {PRODUCT_SHORT}. The default {walkthrough-name}s guide you through the following scenarios:

* Integrating message-oriented middleware with a RESTful API using AMQ Online
* Protecting Applications using Red Hat Single Sign-On (SSO)
* Managing and protecting APIs using API management
* Low-code API development and SaaS integration

In addition, there is a Data Sync Solution Pattern using GraphQL {walkthrough-name} for mobile and web developers.

These {walkthrough-name}s are available in the {webapp}.
