[id='editing-overview-section-solution-pattern']

ifdef::env-github[]
:imagesdir: ../images/
endif::[]

= Editing the overview section of a {PRODUCT} Solution Pattern

The first section of the `walkthrough.adoc` describes your Solution Pattern,it provides an overview of the purpose of the Solution Pattern.
The overview is displayed when a user clicks on the Solution Pattern in {webapp}.

* The overview is defined by a first level heading (in AsciiDoc a line begining with `=`) and finishes at the next second level heading (`==`).
* The title of the overview becomes the name of the Solution Pattern.
* The overview heading must be followed by a paragraph giving a short introduction to the Solution Pattern in one or two sentences.
This description is displayed in the {webapp} dashboard card for the Solution Pattern.

.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding Solution Patterns].


.Procedure
To add an overview section using the template respository:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Change the title of the Solution Pattern, for example:
+
[subs="attributes"]
----
= My first Solution Pattern
----

. Add an introduction paragraph to your preamble.

. Add another paragraph with more information about the Solution Pattern.

. Commit your changes
+
----
git commit -am "add overview"
----

. Push your change to the remote repository
+
----
git push upstream master
----
