= Adding custom services to a {PRODUCT} Solution Pattern

You can create services from the OpenShift catalog in the cluster as part of the Solution Pattern startup process.
You can also link to the URLs associated with those services in your `walkthrough.adoc` file.


.Prerequisites
* You have created a repository using the Solution Pattern template.
* You have added the Solution Pattern repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Publishing Solution Patterns].
* Some experience with the `oc` command. See link:https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html[Getting Started with the OpenShift CLI] for more information about `oc` command.


.Procedure
. Find the name of the service you want to provision:

.. Log in to the OpenShift console.

.. Click your username in the top right corner and choose *Copy Login Command* from the menu.

.. Log in to the OpenShift CLI using the `oc` on your clipboard.

.. Run the following command to list all the service names available from your cluster catalog:
+
----
oc get clusterserviceclasses -o custom-columns="Display Name (From Service Catalog):.spec.externalMetadata.displayName, Identifier (clusterServiceClassExternalName):.spec.externalName"
----
+
The output lists all the services available in two columns:
+
* Display Name (From Service Catalog)
* Identifier (clusterServiceClassExternalName)

.. Choose the service you want to use, and note the value in the `Identifier (clusterServiceClassExternalName)` column.
+
For example, to use the `CakePHP + MySQL (Ephemeral)` service in your custom Solution Pattern, note the value `cakephp-mysql-example`.

. Create a `walkthrough.json` with the following contents to provision the `cakephp-mysql-example` service:
+
----
{
    "dependencies": {
        "repos": [],
        "serviceInstances": [
            {
                "metadata": {
                    "name": "cakephp-mysql-example"
                },
                "spec": {
                    "clusterServiceClassExternalName": "cakephp-mysql-example",
                    "clusterServicePlanExternalName": "default"
                }
            }
        ]
    }
}
----
+
. Add your Solution Pattern to the cluster as described in xref:gs-publishing-walkthroughs-proc[Adding Solution Patterns].
. Navigate the Solution Pattern to trigger the provisioning of the custom service, for example, the `cakephp-mysql-example` service.
. Log in to the OpenShift console.
. Navigate to the custom project in OpenShift.The project is named using the pattern `<username>-<walkthrough-id>`.
. Open *Routes* from the *Applications* menu.
. Note the *Name* of the route you want to reference in your Solution Pattern tasks. For example, `cakephp-mysql-example`.
. Edit the `walkthrough.adoc` file and use the `{route-<route-name>-host}` pattern, whenever you want the route URL to appear.
For example, to insert a step that asks the user of the Solution Pattern to log in to the CakePHP app:
+
----
. Log into the link:{route-cakephp-mysql-example-host}[CakePHP app].
----
+
NOTE: If you want Asciidoc attributes to render values in code blocks, you must start the code block with `[subs="attributes"]`.

+
. Redeploy the *tutorial-web-app* to pick up changes to your Solution Pattern.
. Log in to the {webapp} using a different username to test the Solution Pattern.