[time=10]
== Adding verifications to a {PRODUCT} {walkthrough-name}
Verifications are interactive elements in a {walkthrough-name} that confirm whether a user has successfully completed a procedure. They are questions presented to the user, which can be answered with either a `Yes` or `No` response.

NOTE: Every procedure in a task or subtask requires a verification.


.Prerequisites
* You have created a repository using the {walkthrough-name} template.
* You have added the {walkthrough-name} repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding {walkthrough-name}s].


.Procedure
To add a verification:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. At the end of the procedure section, following the numbered list add:
+
:verificationText: verification
[source,asciidoc,subs="attributes"]
----
[type={verificationText}]
Check that the dashboard of service X reports no errors.
----
. Add the following block to cater for users that answer the question with `No`:
+
[source,asciidoc]
----
[type=verificationFail]
Try turning it off and on again.
----

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.
