= Editing resources for a {PRODUCT} Solution Pattern

The {webapp} can display helpful information and links on the right side panel.

.Prerequisites
* You have created a repository using the Solution Patterns template.
* You have added the Solution Pattern repository to your cluster as described in xref:gs-publishing-walkthroughs-proc[Adding Solution Patterns].


.Procedure
To add a Solution Pattern resources:

. Edit the `walkthroughs/1-template-walkthrough/walkthrough.adoc` file.

. Add Solution Pattern resources using block attributes at the end of the overview section, for example:
+
[source,asciidoc]
----
[type=walkthroughResource,serviceName=openshift]
.OpenShift
****
* link:{openshift-host}[Openshift Console, window="_blank"]
****
----

+
[NOTE]
====
* Setting `serviceName` is optional.

* If `serviceName` is set to the name of a middleware service, an icon indicating the service status is displayed next to the resource.

* For a list of default services, see link:https://github.com/integr8ly/tutorial-web-app/blob/master/src/common/serviceInstanceHelpers.js[the value for DEFAULT_SERVICES].

* Setting the `window="_blank"` parameter for a Solution Pattern resource link is also optional, but ensures that the target of the link displays in a separate browser tab.
====
+
NOTE: You can only define Solution Pattern resources in the overview section.

+

. Save, commit and push your changes.

. Redeploy the {webapp}:
.. Navigate to the *webapp* project in OpenShift.
.. Click on the *tutorial-web-app* deployment config.
.. Click the *Deploy* button.