[id='rn-new-and-changed-ref']
= New and changed features

* Support for TLS 1.0 and TLS 1.1 is removed from {PRODUCT}. Only TLS 1.2 is supported in this release.

* {code-ready-name-short} is upgraded to {code-ready-version}. Existing workspaces are not compatible with this version of {code-ready-name-short}.
+
Red Hat recommends that you recreate any existing workspaces using {code-ready-name-short} {code-ready-version}.

* The following Solution Patterns are not available in this release:
+
--
** _Protecting Applications using Red Hat Single Sign-On (SSO)_.
** _Low-code API development and SaaS integration_.
--
+
Ignore references to these Solution Patterns in the documentation.  

== New component versions

This release includes new versions of the following components:

[cols="h,"]
|===

|Component
|*Release Notes*

|{fuse-name}
|link:{fuse-rn-docs}[{fuse-version}]

|{amq-online-name}
|link:{amq-rn-docs}[{amq-online-version}]

|{three-scale-name}
|link:{three-scale-rn-docs}[{three-scale-version}]

|{code-ready-name}
|link:{code-ready-rn-docs}[{code-ready-version}]

|===
