[id='rn-new-and-changed-ref']
= New and changed features

* Support for TLS 1.0 and TLS 1.1 is removed from {PRODUCT}. Only TLS 1.2 is supported in this release.

* Any {PRODUCT_SHORT} user can now determine which {walkthrough-name}s are available in a cluster. 

* {code-ready-name-short} is upgraded to {code-ready-version}. Existing workspaces are not compatible with this version of {code-ready-name-short}.
+
Red Hat recommends that you recreate any existing workspaces using {code-ready-name-short} {code-ready-version}.

* The following Solution Patterns are not available in this release:
+
--
** _Protecting Applications using Red Hat Single Sign-On (SSO)_.
** _Low-code API development and SaaS integration_.
--
+
Ignore references to these Solution Patterns in the documentation.  

* You can now configure AMQ Online as described in xref:configuring-amq[].

[id='configuring-amq']
== Configuring AMQ Online for production

:cluster-administrator: cluster administrator

If you plan to use AMQ Online in {PRODUCT_SHORT}, you need to create an AMQ Online configuration for production. 
You must edit and apply YAML files using the command line (CLI) tools to configure AMQ Online. 

This section provides general guidance on configuring AMQ Online for production usage in {PRODUCT_SHORT}.

.Prerequisites
* You are a {cluster-administrator} with the OpenShift CLI (`oc`) installed locally.
* You have experience with configuring AMQ Online.

.Procedure

. Configure AMQ Online in {PRODUCT_SHORT} as described in link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.6/html-single/installing_and_managing_amq_online_on_openshift/index#configuring-messaging[Configuring AMQ Online].
+
* The name of the AMQ Online project in your cluster is `enmasse`.
+
* You must log in as `customer-admin`.

. Configure your address space to use an external authentication service as shown in the link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.6/html-single/using_amq_online_on_openshift/index#ref-address-space-example-external-auth-service-override-messaging[address space example using an external authentication service]. 
+
NOTE: The authentication services are configured by the AMQ Online service operator and are specified when creating an address space.
