:PRODUCT: Red Hat Managed Integration
:ProductName: {PRODUCT}
:PRODUCT_SHORT: Managed Integration
:PRODUCT_INIT: rhmi
:PRODUCT_INIT_CAP: RHMI

:imagesdir: _images

:PRODUCT_VERSION: 2
:ProductRelease: {PRODUCT_VERSION}
:MINOR_VERSION_NO: 2.0
:PATCH_VERSION_NO: 2.0.0

:cluster-suffix: <cluster suffix>
:suffix-example: example.u7y2.s1.openshift.com

:URL_COMPONENT_PRODUCT: red_hat_managed_integration
:URL_BASE: https://access.redhat.com/documentation/en-us/red_hat_managed_integration/2/html-single

:URL_BASE_GITHUB: https://github.com/integr8ly/user-documentation

:webapp: Solution Explorer
:walkthrough-name: Solution Pattern

:cluster-administrator: cluster administrator
:cluster-developer: developer user

//:rhmi-sso-name: Managed Integration SSO instance
:customer-sso-name: Customer Application SSO instance
:rhsso-name: Red Hat Single Sign-On

:fuse-name: Red Hat Fuse Online
:fuse-version: 7.5
:fuse-docs: https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/
:fuse-configs: https://access.redhat.com/articles/310603

:amq-online-name: Red Hat AMQ Online
:amq-online-version: 1.3
:amq-online-docs: https://access.redhat.com/documentation/en-us/red_hat_amq/
:amq-online-configs: https://access.redhat.com/articles/2791941

:three-scale-name: Red Hat 3scale API Management
:three-scale-version: 2.8
:three-scale-docs: https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/{three-scale-version}/
:three-scale-configs: https://access.redhat.com/articles/2798521

:code-ready-name: Red Hat CodeReady Workspaces for OpenShift
:code-ready-short: CodeReady Workspaces
:code-ready-version: 2.0
:code-ready-docs: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/{code-ready-version}/
:code-ready-configs: N/A
:codeready-workspaces-url: https://codeready-redhat-rhmi-codeready-workspaces.apps.{cluster-suffix}

:project-note: Projects starting with `redhat-`, `openshift-` and `kube` host cluster components that run as Pods and other infrastructure components. Do not create projects starting with these strings.

// Metadata created by nebel
//
// QuickstartID:
// Level: 1
// ParentAssemblies: generated-master.adoc
// UserStory:
// VerifiedInVersion:
:context: getting-started

[id="getting-started"]
= Getting Started with {PRODUCT} {PRODUCT_VERSION}

This document provides an introduction to {PRODUCT} {PRODUCT_VERSION} for both {cluster-administrator}s and {cluster-developer}s.


:leveloffset: +1

// Metadata created by nebel
//
// QuickstartID:
// Level: 2
// ParentAssemblies: assemblies/getting-started/as_getting-started.adoc
// UserStory:
// VerifiedInVersion:

[id="what-is-rhmi"]
= What is Red Hat Managed Integration?
//In the title of concept modules, include nouns or noun phrases that are used in the body text. This helps readers and search engines find the information quickly.
//Do not start the title of concept modules with a verb. See also _Wording of headings_ in _The IBM Style Guide_.

{PRODUCT} is a hosted and managed integration platform that enables developers to engage in agile, microservices-based application development.

{PRODUCT_SHORT} enables your team to develop, build, and deploy enterprise integration solutions on an OpenShift Dedicated cluster managed by Red Hat.
{PRODUCT_SHORT} enables developers to adopt event-based computing and API-based development with lightweight, loosely coupled, self-service, and flexible components.
With {PRODUCT_SHORT}, selected Red Hat services are integrated, available through a unified web-app, and packaged with instructive integration Solution Patterns to make Red Hat integration more accessible.


{PRODUCT_SHORT} enables your operations team to focus on high-value objectives while Red Hat manages the infrastructure. All of the applications and services are protected by your identity provider.

:leveloffset!:

:leveloffset: +1

// Metadata created by nebel
//
// QuickstartID:
// Level: 2
// ParentAssemblies: assemblies/getting-started/as_getting-started.adoc
// UserStory:
// VerifiedInVersion:

[id="what-is-solution-explorer"]
= What is Solution Explorer?
//In the title of concept modules, include nouns or noun phrases that are used in the body text. This helps readers and search engines find the information quickly.
//Do not start the title of concept modules with a verb. See also _Wording of headings_ in _The IBM Style Guide_.


The {webapp} presents links to the applications available in a {PRODUCT_SHORT} cluster. The {webapp} provides Solution Patterns that guide users through the process of creating various integrated solutions using these applications.


{PRODUCT_SHORT} provides access to the following consoles:

* *OpenShift*, the OpenShift cluster console.

* *API Designer*,  the Apicurito RESTful API visual designer.

* *Red Hat 3scale API Management*, a platform that provide RESTful API Management.

* *Red Hat AMQ*, fast, lightweight, and secure messaging for Internet-scale applications.

* *Red Hat CodeReady Workspaces*, a developer workspace server and cloud IDE.

* *Red Hat Fuse Online*, a facility to obtain data from an application or service, operate on that data, and then send the data to another application or service without writing code.

* *Push Notifications*, a service to push notifications to Android and iOS devices.

* *Red Hat Single Sign-On*, a single sign-on solution for web apps and RESTful web services.

+
[NOTE]
====
Most applications are available in the {webapp} after you log in; however, if *Red Hat AMQ Online* is not available, the *Start service* button is displayed. Click *Start service* to provision it.
====


:leveloffset!:

:leveloffset: +1

// Metadata created by nebel
//
// QuickstartID:
// Level: 2
// ParentAssemblies: assemblies/getting-started/as_getting-started.adoc
// UserStory:
// VerifiedInVersion:

[id="what-are-solution-patterns"]
= What are Solution Patterns?
//In the title of concept modules, include nouns or noun phrases that are used in the body text. This helps readers and search engines find the information quickly.
//Do not start the title of concept modules with a verb. See also _Wording of headings_ in _The IBM Style Guide_.

Solution Patterns are tutorials available in {PRODUCT_SHORT}. The default Solution Patterns guide you through the following scenarios:

* Connecting applications using asynchronous messaging
* Protecting applications using single sign-on
* Low-code API development and SaaS integration
* Protecting APIs using 3scale API Management Platform
* Adding Data Sync to your application with GraphQL


These Solution Patterns are available in the {webapp}.

:leveloffset!:

:leveloffset: +1

:creating-new-dedicated-admins-link: {URl_BASE}/admin-guide/index#creating-new-dedicated-admins

[id="getting-started-admin_{context}"]

= Getting Started with administering a Managed Integration cluster

A Managed Integration cluster is an OpenShift Dedicated cluster.
As a {cluster-administrator} you can perform all the tasks described in link:https://access.redhat.com/documentation/en-us/openshift_dedicated/4/html-single/administering_a_cluster/index[Administering a cluster].

NOTE: This release of {PRODUCT} does not support the task described in the link:https://access.redhat.com/documentation/en-us/openshift_dedicated/4/html-single/getting_started/index[Getting started with OpenShift Dedicated 4].  If you would like to request a change to your cluster that is described in that guide, open a support case on the link:https://access.redhat.com/support/[Red Hat Customer Portal].

A {cluster-administrator} is also an administrator of 3scale and can perform the tasks described in the link:https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/{three-scale-version}/html/admin_portal_guide/index[Admin Portal Guide], noting that Service Discovery is enabled by default.

. Read xref:about-user-sso[].
+
NOTE: A {cluster-administrator} is an administrator of the {customer-sso-name} and can perform all the tasks in the link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.3/html-single/server_administration_guide/index[Server Administration Guide].

. Complete the xref:configuring-github-oauth-for-codeready-workspaces_getting-started[] section so that developers can use CodeReady Workspaces with GitHub.

. Consider creating more {cluster-administrator}s as described in link:{creating-new-dedicated-admins-link}[Creating a new {cluster-administrator}].

NOTE: This release of {PRODUCT} does not support managing groups using the link:https://cloud.redhat.com/openshift[Red Hat OpenShift Cluster Manager] site.


:leveloffset!:

:leveloffset: +2

// Metadata created by nebel
//
// QuickstartID:
// Level: 2
// ParentAssemblies: assemblies/getting-started/as_getting-started.adoc
// UserStory:
// VerifiedInVersion:

[id="about-user-sso"]
= About the {customer-sso-name}

{PRODUCT_SHORT} includes an instance of {rhsso-name} to enable you to protect any applications you deploy on your cluster.

Red Hat manages this instance; however, all {cluster-administrator}s have admin level privileges to configure this instance.

A user named `admin` is used to manage this instance. Do not delete this user.

A {cluster-administrator} typically uses this instance to:

* Create users in the `master` realm.

* Add an Identity Provider in the `master` realm as described in link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.3/html/server_administration_guide/identity_broker[Identity Brokering] to avoid managing the same users in different realms.

* Create and manage new realms.

A {cluster-developer} can create new realms.
{cluster-administrator}s can administer these realms.

.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/[Product Documentation]

:leveloffset!:

:leveloffset: +2

:authorization-callback-url: https://keycloak-edge-redhat-rhmi-rhsso.apps.{cluster-suffix}/auth/realms/openshift/broker/github/endpoint
:github-oauth-secret-url: https://console-openshift-console.apps.{cluster-suffix}/k8s/ns/redhat-rhmi-operator/secrets/github-oauth-secret
:creating-workspace-link: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/html-single/end-user_guide/index#creating-and-configuring-a-new-codeready-workspaces-2.0-workspace

[id="configuring-github-oauth-for-codeready-workspaces_{context}"]
= Configuring GitHub OAuth for CodeReady Workspaces

A GitHub OAuth app allows users to import projects into {code-ready-short} using SSH addresses (`git@`), push to repositories, and use the pull request panel.
This procedure enables automatic SSH key upload to GitHub.

.Procedure

. Register an application on GitHub:
** For GitHub, click https://github.com/settings/profile[Settings] ->
https://github.com/settings/apps[Developer settings] ->
https://github.com/settings/developers[OAuth Apps] ->
https://github.com/settings/applications/new[Register a new OAuth application].
** For GitHub Enterprise, go to your GitHub Enterprise home page and then click
*Settings -> Developer settings -> Register a new application*.
. Enter an application name, for example `CodeReady Workspaces`.
. For the Homepage URL, enter the CodeReady Workspaces URL
+
[subs="attributes"]
----
{codeready-workspaces-url}
----
+
where <cluster-suffix> is the unique sub-domain for your cluster.
For example, {suffix-example}

. Enter the authorization callback URL:
+
[subs="attributes"]
----
{authorization-callback-url}
----
+
where <cluster-suffix> is the unique sub-domain for your cluster.
For example, {suffix-example}

. Click *Register application*.

. Note  the *Client ID* and *Client Secret*. You require these values later in the procedure.

. Log into the OpenShift console as a {cluster-administrator}.

. Navigate to the following URL in your browser:
+
[subs="attributes"]
----
{github-oauth-secret-url}
----
+
where <cluster-suffix> is the unique sub-domain for your cluster.
For example, {suffix-example}

. Select the *Edit Secret* option from the *Actions* menu.
. Enter your GitHub Client ID for the value of *Client Id* and Github Client Secret for the value of *Secret* and click *Save*.
. To validate, create a workspace and connect to GitHub:
.. Log into Solution Explorer as a {cluster-developer}.
.. Navigate to {code-ready-short}.
.. Create a workspace as described in link:{creating-workspace-link}[Creating and configuring a new CodeReady Workspaces 2.0 workspace]
.. Click *Add or Import Project*
.. Click *GitHub*
.. Click *Connect your github account*
.. Click *Authorize*
.. Check that a list of projects is displayed. If projects are not displayed, verify that you followed each step in the procedure above.

:leveloffset!:
